version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=swiftpay
      - DB_PASSWORD=password
      - DB_DATABASE=swiftpay_db
      - STARKNET_RPC_URL=https://alpha-mainnet.starknet.io
      - AUTOSHARE_CONTRACT_ADDRESS=0x0
      - STRK_TOKEN_ADDRESS=0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=swiftpay
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=swiftpay_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 