[sncast.mock-profile1]
account = "mock-deploy"
accounts-file = "/Users/admin/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_8/l3W2omp97bsZzhe8YXQOU"

[sncast.vibes]
account = "vestor"
accounts-file = "/Users/admin/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_8/l3W2omp97bsZzhe8YXQOU"

[sncast.default]
account = "vestor"

[sncast.account8]
account = "account8"
accounts-file = "/Users/owner/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_9/l3W2omp97bsZzhe8YXQOU"

[sncast.mainnet]
account = "minnet"
accounts-file = "/Users/owner/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_9/Z-bu_aTuwBtbfy7YQ4vOS2ZPQgWJpZdw"
