[sncast.swiftpay]
account = "swiftpay"
accounts-file = "/Users/owner/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_8/l3W2omp97bsZzhe8YXQOU"

[sncast.default]
account = "swiftpay"

