[package]
name = "server"
version = "0.1.0"
edition = "2024"
authors = ["Akinshola Akinniyi <akinniyishola@gmail.com>", "Yunus Abdulmajid <example@example.com>"]
description = "A backend API server for Paymesh"
license = "MIT OR Apache-2.0"
repository = "https://github.com/web3Novalabs/paymesh"
readme = "readme.md"
homepage = "https://paymesh.app"
keywords = ["api", "backend", "web", "starknet", "defi", "paymesh"]
categories = ["web-programming"]

[[bin]]
name = "server"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
axum = "0.8.4"
serde = {version="1.0.219", features=["derive"]}
tokio = { version = "1.45.1", features = ["full"] }
starknet = "0.17.0"
dotenvy = "0.15.7"
tower-http = {version="0.6.6", features=["cors","trace"]}
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio-rustls", "chrono", "bigdecimal", "time", "uuid"] }
thiserror = "2.0.16"
serde_json = "1.0.143"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "json", "time"] }
tracing = "0.1.41"
time = { version = "0.3.36", features = ["formatting", "parsing", "serde", "macros"] }
bigdecimal = { version = "0.4.8", features = ["serde"] }
validator = { version = "0.19", features = ["derive"] }
jsonwebtoken = { version = "10.0.0", features = ["rust_crypto"] }
axum-extra = { version = "0.10.3", features = ["cookie"] }
argon2 = "0.5.3"
utoipa = { version = "5.4.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["axum", "vendored"] }
utoipa-axum = "0.2.0"
utoipa-scalar = { version = "0.3.0", features = ["axum"] }
