version: '3'
services:
  api:
    environment:
      RPC_URL: "${RPC_URL}"
      PRIVATE_KEY: "${PRIVATE_KEY}"
      PUBLIC_KEY: "${PUBLIC_KEY}"
      CONTRACT_ADDRESS: "${CONTRACT_ADDRESS}"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"