version: '3.9'
services:
  api:
    image: paymesh/server:${IMAGE_TAG:-latest}
    platform: linux/amd64
    restart: always
    environment:
      RPC_URL: "${RPC_URL}"
      PRIVATE_KEY: "${PRIVATE_KEY}"
      PUBLIC_KEY: "${PUBLIC_KEY}"
      CONTRACT_ADDRESS: "${CONTRACT_ADDRESS}"
      DATABASE_URL: "${DATABASE_URL}"
      CROWD_FUNDING_CONTRACT_ADDRESS: "${CROWD_FUNDING_CONTRACT_ADDRESS}"
      GENESIS_ADMIN_EMAIL: "${GENESIS_ADMIN_EMAIL}"
      GENESIS_ADMIN_PASSWORD: "${GENESIS_ADMIN_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
      JWT_EXPIRED_IN: "${JWT_EXPIRED_IN}"
      JWT_MAXAGE: "${JWT_MAXAGE}"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: "${DATABASE_URL_USER}"
      POSTGRES_PASSWORD: "${DATABASE_URL_PASSWORD}"
      POSTGRES_DB: "${DATABASE_URL_DB}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # indexer:
  #   image: paymesh/the-last-indexer:${IMAGE_TAG:-latest}
  #   restart: always
  #   environment:
  #     DNA_TOKEN: "${DNA_TOKEN}"
  #     API_URL: "${API_URL}"
  #     PAYMESH_API_KEY: "${PAYMESH_API_KEY}"

  
volumes:
  pgdata: