version: '3'
services:
  api:
    image: akshola00/server:latest  # Use the pre-built image
    environment:
      RPC_URL: "${RPC_URL}"
      PRIVATE_KEY: "${PRIVATE_KEY}"
      PUBLIC_KEY: "${PUBLIC_KEY}"
      CONTRACT_ADDRESS: "${CONTRACT_ADDRESS}"
    ports:
      - "8080:8080"
    # Remove the build section since we're using pre-built image