version: '3.9'
services:
  api:
    image: akshola00/server:latest
    platform: linux/amd64
    restart: always
    environment:
      RPC_URL: "${RPC_URL}"
      PRIVATE_KEY: "${PRIVATE_KEY}"
      PUBLIC_KEY: "${PUBLIC_KEY}"
      CONTRACT_ADDRESS: "${CONTRACT_ADDRESS}"
      DATABASE_URL: "${DATABASE_URL}"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: "${DATABASE_URL_USER}"
      POSTGRES_PASSWORD: "${DATABASE_URL_PASSWORD}"
      POSTGRES_DB: "${DATABASE_URL_DB}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  indexer:
    image: akshola00/paymesh-indexer:latest
    environment:
      DNA_TOKEN: "${DNA_TOKEN}"
      API_URL: "${API_URL}"
    mem_limit: 2g  
    depends_on:
      - db   
volumes:
  pgdata:
