services:
  indexer:
    image: paymesh/the-last-indexer:${IMAGE_TAG:-latest}
    restart: always
    environment:
      DNA_TOKEN: "${DNA_TOKEN}"
      API_URL: "${API_URL}"
      PAYMESH_API_KEY: "${PAYMESH_API_KEY}"