import jsPDF from "jspdf";
import { GroupDetails } from "@/types/groups";
import { COLORS } from "./pdf/config";
import { getLogoDataUrl } from "./pdf/helpers";
import { calculateGlobalTotals, calculateMemberStats } from "./pdf/aggregators";
import { drawMembersTable, drawHistoryTable } from "./pdf/tables";

export const generateGroupHistoryPDF = async (groupDetails: GroupDetails) => {
  const doc = new jsPDF();

  // Background
  doc.setFillColor(COLORS.bg[0], COLORS.bg[1], COLORS.bg[2]);
  doc.rect(0, 0, 210, 297, "F");

  // --- Header ---
  doc.setFillColor(COLORS.header[0], COLORS.header[1], COLORS.header[2]);
  doc.rect(0, 0, 210, 50, "F");

  // Logo
  const logoUrl = window.location.origin + "/paymeshLogo.svg";
  const logoData = await getLogoDataUrl(logoUrl);
  if (logoData) {
    doc.addImage(logoData, "PNG", 14, 10, 50, 10.33);
  } else {
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("Paymesh", 14, 20);
  }

  // Header Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Transaction History", 14, 32);

  // --- Group Info ---
  let cursorY = 75;

  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(`Group: ${groupDetails.group_name}`, 14, cursorY);

  cursorY += 8;
  doc.setFontSize(11);
  doc.setTextColor(
    COLORS.secondaryText[0],
    COLORS.secondaryText[1],
    COLORS.secondaryText[2]
  );
  doc.setFont("helvetica", "normal");
  doc.text(`Address: ${groupDetails.group_address}`, 14, cursorY);
  cursorY += 6;
  doc.text(
    `Date Created: ${new Date(groupDetails.created_at).toLocaleString()}`,
    14,
    cursorY
  );

  // --- Total Summary ---
  cursorY += 15;
  doc.setFontSize(14);
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
  doc.setFont("helvetica", "bold");
  doc.text("Total Distributed:", 14, cursorY);

  const globalTotals = calculateGlobalTotals(groupDetails.history);

  cursorY += 8;
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  let summaryText = "";
  Object.entries(globalTotals).forEach(([token, amount]) => {
    if (summaryText) summaryText += "   |   ";
    summaryText += `${token}: ${amount.toFixed(2)}`;
  });
  if (!summaryText) summaryText = "No transactions found.";

  doc.text(summaryText, 14, cursorY);

  // --- Members Summary Table ---
  cursorY += 12;
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Group Members:", 14, cursorY);

  const memberStats = calculateMemberStats(groupDetails.history);
  cursorY = drawMembersTable(doc, memberStats, cursorY + 5);

  // --- Transaction History Table ---
  cursorY += 15;
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Transaction History:", 14, cursorY);

  if (groupDetails.history.length > 0) {
    cursorY = drawHistoryTable(doc, groupDetails.history, cursorY + 5);
  } else {
    cursorY += 10;
    doc.setFontSize(11);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(
      COLORS.secondaryText[0],
      COLORS.secondaryText[1],
      COLORS.secondaryText[2]
    );
    doc.text("No transaction history available.", 14, cursorY);
  }

  // --- Footer ---
  const finalY = cursorY || 85;
  doc.setFontSize(9);
  doc.setTextColor(
    COLORS.secondaryText[0],
    COLORS.secondaryText[1],
    COLORS.secondaryText[2]
  );

  doc.text("Generated by Paymesh", 14, finalY + 10);
  doc.text(new Date().toLocaleString(), 14, finalY + 15);

  doc.save(
    `Paymesh_History_${groupDetails.group_name.replace(/\\s+/g, "_")}.pdf`
  );
};
